site_name: observability-mtl-instrument
repo_url: https://github.com/SergioRicJr/observability-mtl-instrument
repo_name: observability-mtl-instrument
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR

markdown_extensions: 
  -  attr_list

extra_css:
  - stylesheets/extra.css