{
 "title": "fastapi-observability",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de requisições nas últimas 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_total_by_code_total[1d])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Porcentagem de requisições por código http",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total_by_code_total[30m])",
     "legendFormat": "{{http_code}}"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_duration_seconds_sum{job=\"fastapi-app\", unmapped=\"False\"} / http_requests_duration_seconds_count{job=\"fastapi-app\", unmapped=\"False\"}",
     "legendFormat": "{{http_method}} - {{url_path}}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "round(increase(http_requests_duration_seconds_count{unmapped=\"False\"}[1m]))",
     "legendFormat": "{{http_method}} - {{url_path}}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições em progresso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "request_in_progress_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Porcentagem de logs por tipo",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (rate({job=\"fastapi-app\"}[30m]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "{job=~\"fastapi-app\"} | logfmt | line_format \"{{.job}}\\t{{.severity}}\\t trace_id={{.trace_id}}\\t {{.message}}\" "
    }
   ]
  }
 ]
}