version: '3'
services:
  fastapi-app:
    container_name: fastapi-app
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - observability-network

networks:
  observability-network:
    external:
      name: observability-network